### ISSUE TITLE
Corrupt Client Dependency Config File

### ISSUE THREAD

**Issue by 0Neji** [SteveEdson/bump-client-dependency#4]
Nice work on this - now using this on a couple of sites and works a treat, I did run into one issue however with a fresh installation of Umbraco.

The ([client dependency](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI/config/ClientDependency.Release.config) version out-of-the-box is `1`. So when I ran this it bumped up the number just fine but it also bumped the XML version number to `2.0`

It's the first line:
```
<?xml version="1.0" encoding="utf-8"?>
```

Which gets changed to:
```
<?xml version="2.0" encoding="utf-8"?>
```

I also tested this when my client dependency version was 8 at it bumped the encoding from `utf-8` to `utf-9` - again, on the first line of the file:

```
<?xml version="1.0" encoding="utf-8"?>
```

```
<?xml version="1.0" encoding="utf-9"?>
```

Easy to fix by starting with a different version number but thought I'd raise the issue as it'll be a little more friendly to use with a fresh Umbraco installation.

Thanks!

**Comment by SteveEdson** [comment]
Thanks! Should be fixed now if you could test again please?
